<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DomainTypes.fs" />
    <Compile Include="Evaluator.fs" />
    <Compile Include="View.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="4.5.0" />
    <PackageReference Include="Fable.Elmish" Version="4.3.0" />
    <PackageReference Include="Fable.Elmish.React" Version="4.0.0" />
    <PackageReference Include="Fable.React" Version="9.4.0" />
    <PackageReference Include="Feliz" Version="2.9.0" />
    <PackageReference Include="Thoth.Fetch" Version="3.0.1" />
    <PackageReference Include="Thoth.Json" Version="10.4.1" />
    <PackageReference Include="Thoth.Json.Net" Version="12.0.0" />
  </ItemGroup>

</Project>
